### ISSUE TITLE
Import error when loading xmitgcm with xarray 0.12.1

### ISSUE THREAD

**Issue by tatsumonkman47** [xgcm/xmitgcm#151]
I get an import error when importing xmitgcm with xarray-0.12.1 (python 3.6.0). It looks like the "OrderedDict" name in xarray.core.pycompat has been removed, and thus when I import xmitgcm I get the following error:

`
>>> import xmitgcm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/anaconda2/lib/python3.6/site-packages/xmitgcm/__init__.py", line 2, in <module>
    from .mds_store import open_mdsdataset
  File "/home/anaconda2/lib/python3.6/site-packages/xmitgcm/mds_store.py", line 19, in <module>
    from .variables import dimensions, \
  File "/home/anaconda2/lib/python3.6/site-packages/xmitgcm/variables.py", line 8, in <module>
    from xarray.core.pycompat import OrderedDict
ImportError: cannot import name 'OrderedDict'
`

Any word on a fix?

**Comment by rabernat** [comment]
What version of xmitgcm are you using?

A similar error was identified and fixed in #123. If you upgrade to v0.3.0, I think your problem will disappear.

**Comment by tatsumonkman47** [comment]
Great, thank you! For reference the xmitgcm that I'm seeing on conda-forge is still version 0.2.2, so that seems to be what caused the confusion. Pip has version 0.3.0

**Comment by tatsumonkman47** [comment]
I was using 0.2.2

**Comment by rabernat** [comment]
Great! And you helped identify the stalled conda-forge update: https://github.com/conda-forge/xmitgcm-feedstock/pull/1

Someone has to merge that PR, but I don't know who has rights to do it.

**Comment by raphaeldussin** [comment]
@rabernat do we need to update our conda recipe? or is it done automatically?
